### ISSUE TITLE
Banner initially sizes image for mobile

### ISSUE THREAD

**Issue by echalifour** [pjehan/wp-plugin-owlcarousel#6]
Hi! We're using owlcarousel on our company website cabinetstogo.com. On the product pages the banner image initially sizes to 621x239 regardless of the window size. You can see this in action here: http://cabinetstogo.com/product/kitchen-cabinets/aspen-white Note: this is only happening in Chrome, it seems. Any help, even if it's just direction on where to put a responsive function call to trick it into resizing itself, would be very appreciated.

Thanks,
Eric

**Comment by pjehan** [comment]
Hi!

Unfortunately, you're not using the Wordpress plugin I created and I think your problem is more related to the original Owl Carousel Javascript and the CSS.

**Comment by echalifour** [comment]
ah, gotcha. Thanks
